# Generated by Django 6.0.7 on 2026-07-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_merge_20260725_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='guaranted_id',
        ),
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tabungan', to='member.member'),
        ),
        migrations.CreateModel(
            name='Jaminan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_penjamin', models.CharField(choices=[('bpkb', 'BPKB'), ('surat_tanah', 'Surat Tanah'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Jenis Penjamin')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jaminan', to='member.member', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Jaminan',
                'verbose_name_plural': 'Jaminan',
            },
        ),
    ]
