# Generated by Django 6.0.7 on 2026-07-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_merge_20260725_0000'),
    ]

    operations = [
        # Idempotent di level DB: kolom ini juga di-drop oleh cabang 0008_drop_legacy_guaranted_id,
        # sehingga pada DB baru kolom bisa sudah tidak ada saat migrasi ini dijalankan.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE member_member DROP COLUMN IF EXISTS guaranted_id_id;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='member',
                    name='guaranted_id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tabungan', to='member.member'),
        ),
        # Idempotent di level DB: tabel juga dibuat oleh cabang 0007_add_jaminan_and_monthly_loan.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        CREATE TABLE IF NOT EXISTS member_jaminan (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            jenis_penjamin varchar(20) NOT NULL,
                            keterangan text NOT NULL,
                            created_at timestamp with time zone NOT NULL,
                            member_id bigint NOT NULL REFERENCES member_member(id) DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE INDEX IF NOT EXISTS member_jaminan_member_id_idx ON member_jaminan (member_id);
                        """
                    ),
                    reverse_sql='DROP TABLE IF EXISTS member_jaminan CASCADE;',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Jaminan',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('jenis_penjamin', models.CharField(choices=[('bpkb', 'BPKB'), ('surat_tanah', 'Surat Tanah'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Jenis Penjamin')),
                        ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jaminan', to='member.member', verbose_name='Anggota')),
                    ],
                    options={
                        'verbose_name': 'Jaminan',
                        'verbose_name_plural': 'Jaminan',
                    },
                ),
            ],
        ),
    ]
