# Generated by Django 6.0.7 on 2026-07-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_merge_20260725_0000'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        CREATE TABLE IF NOT EXISTS member_jaminan (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            jenis_penjamin varchar(20) NOT NULL,
                            keterangan text NOT NULL,
                            created_at timestamp with time zone NOT NULL,
                            member_id bigint NOT NULL REFERENCES member_member(id) DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE INDEX IF NOT EXISTS member_jaminan_member_id_idx ON member_jaminan (member_id);
                        """
                    ),
                    reverse_sql=(
                        """
                        DROP TABLE IF EXISTS member_jaminan CASCADE;
                        """
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Jaminan',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('jenis_penjamin', models.CharField(choices=[('bpkb', 'BPKB'), ('surat_tanah', 'Surat Tanah'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Jenis Penjamin')),
                        ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jaminan', to='member.member', verbose_name='Nomor Anggota')),
                    ],
                    options={
                        'verbose_name': 'Jaminan',
                        'verbose_name_plural': 'Jaminan',
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Nomor Pinjaman Bulanan')),
                ('loan_date', models.DateField(verbose_name='Tanggal Peminjaman')),
                ('installment_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Jumlah Angsuran')),
                ('loan_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Jumlah Pinjaman')),
                ('installment_duration', models.PositiveIntegerField(editable=False, verbose_name='Lama Angsuran')),
                ('status', models.CharField(choices=[('proses', 'Proses'), ('lunas', 'Lunas'), ('telat', 'Telat')], default='proses', max_length=10, verbose_name='Status Pinjaman')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jaminan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_loans', to='member.jaminan', verbose_name='ID Jaminan')),
                ('loan_rate_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_loans', to='member.loanratetable', verbose_name='Daftar Pinjaman Bulanan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_loans', to='member.member', verbose_name='Nomor Anggota')),
            ],
            options={
                'verbose_name': 'Pinjaman Bulanan',
                'verbose_name_plural': 'Pinjaman Bulanan',
                'ordering': ['-loan_date', '-created_at'],
            },
        ),
    ]
