# Generated by Django 6.0.7 on 2026-07-25 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_drop_legacy_guaranted_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanratetable',
            options={'verbose_name': 'Tabel Tarif Pinjaman', 'verbose_name_plural': 'Tabel Tarif Pinjaman'},
        ),
        migrations.AlterModelOptions(
            name='loanrule',
            options={'verbose_name': 'Aturan Pinjaman', 'verbose_name_plural': 'Aturan Pinjaman'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Anggota', 'verbose_name_plural': 'Anggota'},
        ),
        migrations.AlterModelOptions(
            name='savings',
            options={'verbose_name': 'Tabungan', 'verbose_name_plural': 'Tabungan'},
        ),
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Transaksi Tabungan', 'verbose_name_plural': 'Transaksi Tabungan'},
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_member',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Anggota'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_month',
            field=models.CharField(blank=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'ID bulanan harus tepat 4 digit (0001-9999).')], verbose_name='ID Bulanan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_week',
            field=models.CharField(blank=True, max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'ID mingguan harus tepat 3 digit (001-999).')], verbose_name='ID Mingguan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Nomor Telepon'),
        ),
    ]
