# Generated by Django 6.0.7 on 2026-07-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_merge_20260725_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaminan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jaminan', to='member.member', verbose_name='Nomor Anggota'),
        ),
    ]
