# Generated by Django 6.0.7 on 2026-10-08 13:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_jaminan_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Jumlah uang transaksi', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Jumlah transaksi harus lebih dari 0.')]),
        ),
    ]
