# Generated by Django 6.0.7 on 2026-10-08 14:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models



def backfill_loan_fees(apps, schema_editor):
    """Pinjaman lama (semuanya bulanan) belum punya snapshot biaya admin & jumlah dicairkan."""
    Loan = apps.get_model('member', 'Loan')
    for loan in Loan.objects.select_related('loan_rate_table'):
        loan.admin_fee = loan.loan_rate_table.admin_fee
        loan.disbursed_amount = loan.loan_amount - loan.admin_fee
        loan.save(update_fields=['admin_fee', 'disbursed_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_rename_monthlyloan_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Jumlah pembayaran harus lebih dari 0.')], verbose_name='Jumlah Bayar')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal Bayar')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pembayaran Pinjaman',
                'verbose_name_plural': 'Pembayaran Pinjaman',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Jumlah denda harus lebih dari 0.')], verbose_name='Jumlah Denda')),
                ('penalty_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal Denda')),
                ('reason', models.TextField(verbose_name='Alasan')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Sudah Dibayar')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Dibayar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Denda Pinjaman',
                'verbose_name_plural': 'Denda Pinjaman',
                'ordering': ['-penalty_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date', '-created_at'], 'verbose_name': 'Pinjaman', 'verbose_name_plural': 'Pinjaman'},
        ),
        migrations.AddField(
            model_name='loan',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Biaya Admin'),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Jumlah pinjaman dikurangi biaya admin.', max_digits=15, verbose_name='Jumlah Dicairkan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('weekly', 'Mingguan'), ('monthly', 'Bulanan')], default='monthly', editable=False, help_text='Otomatis mengikuti jenis aturan pada tarif pinjaman.', max_length=10, verbose_name='Jenis Pinjaman'),
        ),
        migrations.AddField(
            model_name='member',
            name='inactive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Nonaktif'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='jaminan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jaminan', to='member.member', verbose_name='Nomor Anggota'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='jaminan',
            field=models.ForeignKey(blank=True, help_text='Wajib untuk pinjaman bulanan.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='member.jaminan', verbose_name='ID Jaminan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Nomor Pinjaman'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_rate_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='member.loanratetable', verbose_name='Tarif Pinjaman'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='member.member', verbose_name='Nomor Anggota'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('proses', 'Proses'), ('lunas', 'Lunas'), ('telat', 'Telat')], default='proses', editable=False, max_length=10, verbose_name='Status Pinjaman'),
        ),
        migrations.AlterField(
            model_name='loanratetable',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, help_text='Besar angsuran per periode (minggu/bulan)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanratetable',
            name='installment_count',
            field=models.PositiveIntegerField(help_text='Jumlah cicilan (minggu untuk pinjaman mingguan, bulan untuk bulanan)'),
        ),
        migrations.AlterField(
            model_name='loanratetable',
            name='loan_rule',
            field=models.ForeignKey(help_text='Aturan pinjaman (mingguan atau bulanan)', on_delete=django.db.models.deletion.CASCADE, related_name='rate_tables', to='member.loanrule'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='member.savings'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'lunas'), _negated=True), fields=('member', 'loan_type'), name='unique_active_loan_per_member_type', violation_error_message='Anggota masih memiliki pinjaman sejenis yang belum lunas.'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('jaminan__isnull', False), models.Q(('status', 'lunas'), _negated=True)), fields=('jaminan',), name='unique_jaminan_per_active_loan', violation_error_message='Jaminan masih dipakai pinjaman lain yang belum lunas.'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='member.loan', verbose_name='Pinjaman'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat oleh'),
        ),
        migrations.AddField(
            model_name='loanpenalty',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='member.loan', verbose_name='Pinjaman'),
        ),
        migrations.AddField(
            model_name='loanpenalty',
            name='recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat oleh'),
        ),
        migrations.RunPython(backfill_loan_fees, migrations.RunPython.noop),
    ]
