# Generated by Django 6.0.7 on 2026-10-08 23:00

from django.db import migrations, models



def backfill_loan_numbers(apps, schema_editor):
    """Nomor pinjaman lama (urutan global) diganti ID anggota; urutan ke-n per anggota & jenis."""
    Loan = apps.get_model('member', 'Loan')
    last_sequence = {}
    for loan in Loan.objects.select_related('member').order_by('loan_date', 'created_at', 'pk'):
        member = loan.member
        loan.loan_number = member.id_week if loan.loan_type == 'weekly' else member.id_month
        key = (loan.member_id, loan.loan_type)
        last_sequence[key] = last_sequence.get(key, 0) + 1
        loan.sequence = last_sequence[key]
        loan.save(update_fields=['loan_number', 'sequence'])

    # Jalankan trigger FK yang tertunda agar AddConstraint berikutnya bisa ALTER TABLE
    # dalam transaksi yang sama (Postgres: "pending trigger events").
    schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_loan_types_payments_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Urutan pinjaman anggota untuk jenis yang sama.', verbose_name='Pinjaman ke-'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(db_index=True, editable=False, help_text='Mingguan: ID Mingguan anggota. Bulanan: ID Bulanan anggota.', max_length=4, verbose_name='Nomor Pinjaman'),
        ),
        migrations.RunPython(backfill_loan_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('member', 'loan_type', 'sequence'), name='unique_loan_sequence_per_member_type'),
        ),
    ]
