# Generated by Django 6.0.7 on 2026-10-08 23:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone



def convert_member_savings(apps, schema_editor):
    """
    Akun tabungan otomatis per anggota diubah menjadi rekening simpanan sukarela:
    akun tanpa transaksi dihapus; akun bertransaksi dipertahankan dengan nomor sementara
    LAMA-<id> yang perlu diganti petugas dengan nomor buku tabungan.
    """
    Savings = apps.get_model('member', 'Savings')
    SavingsProduct = apps.get_model('member', 'SavingsProduct')
    Nasabah = apps.get_model('member', 'Nasabah')

    product, _ = SavingsProduct.objects.get_or_create(
        code='sukarela', defaults={'name': 'Simpanan Sukarela'},
    )

    Savings.objects.filter(transactions__isnull=True).delete()

    for savings in Savings.objects.select_related('member'):
        member = savings.member
        nasabah = Nasabah.objects.create(
            name=member.name,
            address=member.address,
            phone_number=member.phone_number,
            member=member,
        )
        savings.nasabah = nasabah
        savings.product = product
        savings.account_number = f'LAMA-{savings.pk}'
        # Transaksi lama bisa bertanggal sebelum akun dibuat; tanggal buka = yang paling awal.
        first_tx = savings.transactions.order_by('transaction_date').values_list('transaction_date', flat=True).first()
        savings.opened_date = min(timezone.localdate(savings.created_at), first_tx)
        savings.save(update_fields=['nasabah', 'product', 'account_number', 'opened_date'])

    # Jalankan trigger FK tertunda sebelum migrasi berikutnya mengubah struktur tabel.
    schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_loan_number_follows_member_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsInterestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Berlaku Mulai')),
                ('annual_rate', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bunga (% per tahun)')),
                ('basis', models.CharField(choices=[('lowest_balance', 'Saldo terendah dalam periode'), ('end_balance', 'Saldo akhir periode'), ('average_daily_balance', 'Rata-rata saldo harian')], default='lowest_balance', max_length=30, verbose_name='Dasar Perhitungan')),
                ('min_balance_for_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saldo Minimum Dapat Bunga')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aturan Bunga Simpanan',
                'verbose_name_plural': 'Aturan Bunga Simpanan',
                'ordering': ['product', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='Kode')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('min_balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo yang harus tersisa setelah penarikan.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saldo Minimum Mengendap')),
                ('allow_withdrawal', models.BooleanField(default=True, verbose_name='Boleh Ditarik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Jenis Simpanan',
                'verbose_name_plural': 'Jenis Simpanan',
            },
        ),
        migrations.AlterModelOptions(
            name='savings',
            options={'ordering': ['account_number'], 'verbose_name': 'Rekening Simpanan', 'verbose_name_plural': 'Rekening Simpanan'},
        ),
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Transaksi Simpanan', 'verbose_name_plural': 'Transaksi Simpanan'},
        ),
        migrations.AddField(
            model_name='savings',
            name='account_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AddField(
            model_name='savings',
            name='closed_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Tanggal Tutup'),
        ),
        migrations.AddField(
            model_name='savings',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='savings',
            name='opened_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal Buka'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='interest_period',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Periode Bunga'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat oleh'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Saldo tabungan saat ini', max_digits=15, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabungan', to='member.member'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='member.savings', verbose_name='Rekening'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Tanggal transaksi'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Setor'), ('withdrawal', 'Ambil'), ('interest', 'Bunga')], max_length=20, verbose_name='Jenis Transaksi'),
        ),
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Nasabah')),
                ('nik', models.CharField(blank=True, max_length=20, verbose_name='NIK')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(blank=True, help_text='Kosongkan jika nasabah bukan anggota koperasi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nasabah', to='member.member', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Nasabah',
                'verbose_name_plural': 'Nasabah',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='savings',
            name='nasabah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rekening', to='member.nasabah', verbose_name='Nasabah'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='interest_rule',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='member.savingsinterestrule', verbose_name='Aturan Bunga'),
        ),
        migrations.AddConstraint(
            model_name='savingstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'interest')), fields=('savings', 'interest_period'), name='unique_interest_posting_per_period'),
        ),
        migrations.AddField(
            model_name='savingsinterestrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_rules', to='member.savingsproduct', verbose_name='Jenis Simpanan'),
        ),
        migrations.AddField(
            model_name='savings',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='member.savingsproduct', verbose_name='Jenis Simpanan'),
        ),
        migrations.AddConstraint(
            model_name='nasabah',
            constraint=models.UniqueConstraint(condition=models.Q(('nik', ''), _negated=True), fields=('nik',), name='unique_nasabah_nik', violation_error_message='NIK sudah terdaftar sebagai nasabah.'),
        ),
        migrations.AddConstraint(
            model_name='savingsinterestrule',
            constraint=models.UniqueConstraint(fields=('product', 'effective_from'), name='unique_interest_rule_per_product_date', violation_error_message='Sudah ada aturan bunga untuk jenis simpanan & tanggal berlaku ini.'),
        ),
        migrations.RunPython(convert_member_savings, migrations.RunPython.noop),
    ]
