# Generated by Django 6.0.7 on 2026-10-08 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_savings_accounts_nasabah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='member',
        ),
        migrations.AlterField(
            model_name='savings',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='nasabah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rekening', to='member.nasabah', verbose_name='Nasabah'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='member.savingsproduct', verbose_name='Jenis Simpanan'),
        ),
        migrations.AddConstraint(
            model_name='savings',
            constraint=models.UniqueConstraint(fields=('nasabah', 'product'), name='unique_account_per_nasabah_product', violation_error_message='Nasabah sudah memiliki rekening untuk jenis simpanan ini.'),
        ),
    ]
