# Generated by Django 6.0.7 on 2026-10-08 23:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models



def create_member_savings_products(apps, schema_editor):
    """Simpanan pokok (sekali) & wajib (bulanan) hanya bisa ditarik saat anggota keluar; nominal diatur di admin."""
    SavingsProduct = apps.get_model('member', 'SavingsProduct')
    for code, name, billing in [
        ('pokok', 'Simpanan Pokok', 'once'),
        ('wajib', 'Simpanan Wajib', 'monthly'),
    ]:
        SavingsProduct.objects.update_or_create(
            code=code,
            defaults={'name': name, 'billing': billing, 'withdraw_only_on_exit': True, 'allow_withdrawal': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_savings_accounts_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsproduct',
            name='billing',
            field=models.CharField(choices=[('none', 'Bebas (tanpa kewajiban)'), ('once', 'Sekali (boleh dicicil)'), ('monthly', 'Tiap bulan')], default='none', help_text='Nominal kewajiban diatur di menu Nominal Simpanan.', max_length=10, verbose_name='Kewajiban Setor'),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='withdraw_only_on_exit',
            field=models.BooleanField(default=False, help_text='Penarikan hanya diizinkan bila anggota pemilik sudah nonaktif (keluar).', verbose_name='Tarik Hanya Saat Keluar'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='account_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nomor Rekening'),
        ),
        migrations.CreateModel(
            name='MemberSavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='ID Akun Simpanan')),
                ('opened_date', models.DateField(default=django.utils.timezone.localdate, help_text='Simpanan wajib ditagih mulai bulan ini.', verbose_name='Tanggal Buka')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Aktif')),
                ('closed_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Tanggal Tutup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='akun_simpanan', to='member.member', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Akun Simpanan Anggota',
                'verbose_name_plural': 'Akun Simpanan Anggota',
                'ordering': ['account_number'],
            },
        ),
        migrations.AddField(
            model_name='savings',
            name='member_account',
            field=models.ForeignKey(blank=True, editable=False, help_text='Terisi untuk sub-rekening simpanan pokok & wajib.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='member.membersavingsaccount', verbose_name='Akun Simpanan Anggota'),
        ),
        migrations.CreateModel(
            name='SavingsDueRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Berlaku Mulai')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Nominal')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_rates', to='member.savingsproduct', verbose_name='Jenis Simpanan')),
            ],
            options={
                'verbose_name': 'Nominal Simpanan',
                'verbose_name_plural': 'Nominal Simpanan',
                'ordering': ['product', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('product', 'effective_from'), name='unique_due_rate_per_product_date', violation_error_message='Sudah ada nominal untuk jenis simpanan & tanggal berlaku ini.')],
            },
        ),
        migrations.RunPython(create_member_savings_products, migrations.RunPython.noop),
    ]
